name: 'Upload to S3'
description: ''
inputs:
  MESSAGE_TEXT:
    description: 'Comment'
    required: true
    default: 'None'
  SLACK_TOKEN:
    description: 'SLACK TOKEN'
    required: true
    default: 'no token'
  CHANNELS:
    description: 'Slack channels ID where message will be posted (separated with ,)'
    required: true
    default: '' 
  FILENAME:
    description: 'Attachment'
    required: false
    default: ''
  TIMEOUT:
    description: 'for large files'
    required: false
    default: '74'
  ERROR_TEXT:
    description: 'Message, if file was not uploaded'
    required: false
    default: '⚠ Ошибка прикрепления файла'


runs:
  using: "composite"
  steps: 
    - name: Send via curl
      shell: bash
      run: |
        response=$(curl --connect-timeout 74 -F file=@${{ inputs.FILENAME }} \
                -F "initial_comment=${{ inputs.MESSAGE_TEXT }}" \
                -F channels=${{ inputs.CHANNELS }} \
                -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" \
                https://slack.com/api/files.upload)
        echo step 0 - ok
        STATUS=$($response | jq -r ".ok") >> $GITHUB_ENV
        echo step 0.1 - ok
        echo "STATUS=$STATUS" >> $GITHUB_ENV
        echo step 0.2 - ok
        echo $response | jq -r
        echo step 1 - ok

    - name: Check status
      if: env.STATUS == 'false'
      shell: bash
      run: |
        response=$(curl --connect-timeout ${{ inputs.TIMEOUT }} \
                -d text="${{ inputs.MESSAGE_TEXT }}${{ inputs.ERROR_TEXT }}" \
                -d channel=${{ inputs.CHANNELS }} \
                -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" \
                https://slack.com/api/chat.postMessage)
        echo TS=$($response | jq -r ".ts") >> $GITHUB_ENV
        echo $response | jq -r
        echo "Emoji"
        sleep 3
        response=$(curl --connect-timeout 74 \
                -d text=":card_file_box:" \
                -d thread_ts=$TS \
                -d channel=${{ inputs.CHANNELS }} \
                -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" \
                https://slack.com/api/chat.postMessage)
        echo $response | jq -r
