name: 'Upload to S3'
description: ''
inputs:
  MESSAGE_TEXT:
    description: 'Comment'
    required: true
    default: 'None'
  SLACK_TOKEN:
    description: 'SLACK TOKEN'
    required: true
    default: 'no token'
  CHANNELS:
    description: 'Slack channels ID where message will be posted (separated with ,)'
    required: true
    default: '' 
  FILENAME:
    description: 'Attachment'
    required: false
    default: ''

runs:
  using: "composite"
  steps: 
    - name: Send via curl
      shell: bash
      run: |
        curl --data-binary -F file=@${{ inputs.FILENAME }} \
        -F "initial_comment=${{ inputs.MESSAGE_TEXT }}" \
        -F channels=${{ inputs.CHANNELS }} \
        -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" https://slack.com/api/files.upload | sleep 120