name: 'Upload to S3'
description: ''
inputs:
  BOTKEY:
    description: 'TELEGRAM BOTKEY'
    required: true
    default: ''
  CHAT_ID:
    description: 'TELEGRAM CHATID'
    required: true
    default: ''
  MESSAGE_TEXT:
    description: 'TEXT'
    required: true
    default: 'None'


runs:
  using: "composite"
  steps: 
    - name: Install lybraries 
      shell: bash
      run: |
        pip3 install slack_sdk
        pip3 install pytelegrambotapi # for testing

    - name: Run Scripts
      shell: python3 {0}
      run: |
        import telebot
        tbot = telebot.TeleBot(${{ inputs.BOTKEY }}, None)
        tbot.send_message(chat_id="${{ inputs.CHAT_ID }}", text=f"${{ inputs.MESSAGE_TEXT }}", parse_mode='html')