name: 'Upload to S3'
description: ''
inputs:
  MESSAGE_TEXT:
    description: 'Comment'
    required: true
    default: 'None'
  SLACK_TOKEN:
    description: 'SLACK TOKEN'
    required: true
    default: 'no token'
  CHANNELS:
    description: 'Slack channels ID where message will be posted (separated with ,)'
    required: true
    default: '' 
  FILENAME:
    description: 'Attachment'
    required: false
    default: ''

runs:
  using: "composite"
  steps: 
    - name: Install slack_sdk 
      shell: bash
      run: pip3 install slack_sdk

    - name: Run Script
      shell: python3 {0}
      run: |
        from slack_sdk import WebClient
        from slack_sdk.errors import SlackApiError

        client = WebClient(token="${{ inputs.SLACK_TOKEN }}")

        if "${{ inputs.FILENAME }}":
          result = client.files_upload(channels="${{ inputs.CHANNELS }}",
                                       initial_comment="""${{ inputs.MESSAGE_TEXT }}""",
                                       file="${{ inputs.FILENAME }}",)
          print(f"Result is:\n{result}")
        else:
          response = client.chat_postMessage(channel="${{ inputs.CHANNELS }}", text="""${{ inputs.MESSAGE_TEXT }}""" )
          print(response)