name: 'Upload to S3'
description: ''
inputs:
  MESSAGE_TEXT:
    description: 'Comment'
    required: true
    default: 'None'
  SLACK_TOKEN:
    description: 'SLACK TOKEN'
    required: true
    default: 'no token'
  CHANNELS:
    description: 'Slack channels ID where message will be posted (separated with ,)'
    required: true
    default: '' 
  FILENAME:
    description: 'Attachment'
    required: false
    default: ''
  TIMEOUT:
    description: 'for large files'
    required: false
    default: '74'
  ERROR_TEXT:
    description: 'Message, if file was not uploaded'
    required: false
    default: '⚠ Ошибка прикрепления файла'


runs:
  using: "composite"
  steps: 
    - name: Send Text
      shell: bash
      run: |
        echo "Send Message to Slack"
        response=$(curl --connect-timeout ${{ inputs.TIMEOUT }} \
                -d text="${{ inputs.MESSAGE_TEXT }}" \
                -d channel=${{ inputs.CHANNELS }} \
                -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" \
                https://slack.com/api/chat.postMessage)
        echo TS=$($response | jq -r ".ts") >> $GITHUB_ENV

    - name: Check status and Send again curl
      if: inputs.FILENAME != ''
      shell: bash
      run: |
        echo "Send file({{ inputs.FILENAME }}) to Slack"
        response=$(curl --connect-timeout ${{ inputs.TIMEOUT }} \
                -F file=@${{ inputs.FILENAME }} \
                -F thread_ts=${{ env.TS }} \
                -F channels=${{ inputs.CHANNELS }} \
                -H "Authorization: Bearer ${{ inputs.SLACK_TOKEN }}" \
                https://slack.com/api/files.upload)
        echo $response