name: Test bot

on:
  push:
    branches:
      - telegram

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - uses: Jnqa/Slack-send@main
        with: 
          BOTKEY: ${{ secrets.BOTKEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_TEXT: ${{ github.run_id	}}